In [1]:
import pandas as pd
from dfply import *

In [52]:
Poverty_Estimates = pd.read_csv("/home/mcleodgunne/Mod2HW/PovertyEstimates1.csv")
Poverty_Estimates = (Poverty_Estimates >> mutate(State = X.Stabr))
Poverty_Estimates

,FIPS_code,Stabr,Area_name,Rural-urban_Continuum_Code_2003,Urban_Influence_Code_2003,Rural-urban_Continuum_Code_2013,Urban_Influence_Code_2013,POVALL_2020,CI90LBALL_2020,CI90UBALL_2020,...,POV517_2020,CI90LB517_2020,CI90UB517_2020,PCTPOV517_2020,CI90LB517P_2020,CI90UB517P_2020,MEDHHINC_2020,CI90LBINC_2020,CI90UBINC_2020,State
0,0,US,United States,NaN,NaN,NaN,NaN,"38,371,394","38,309,115","38,433,673",...,"7,798,566","7,778,138","7,818,994",14.9,14.9,14.9,"67,340","67,251","67,429",US
1,1000,AL,Alabama,NaN,NaN,NaN,NaN,"714,568","695,249","733,887",...,"152,810","144,819","160,801",19.7,18.7,20.7,"53,958","53,013","54,903",AL
2,1001,AL,Autauga County,2.0,2.0,2.0,2.0,"6,242","4,930","7,554",...,"1,378",926,"1,830",14.5,9.7,19.3,"67,565","59,132","75,998",AL
3,1003,AL,Baldwin County,4.0,5.0,3.0,2.0,"20,189","15,535","24,843",...,"4,192","2,677","5,707",11.8,7.5,16.1,"71,135","66,540","75,730",AL
4,1005,AL,Barbour County,6.0,6.0,6.0,6.0,"5,548","4,210","6,886",...,"1,303",888,"1,718",35.8,24.4,47.2,"38,866","33,510","44,222",AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3190,56037,WY,Sweetwater County,5.0,8.0,5.0,8.0,"3,187","2,435","3,939",...,587,360,814,7.3,4.5,10.1,"70,583","61,835","79,331",WY
3191,56039,WY,Teton County,7.0,8.0,7.0,8.0,"1,207",896,"1,518",...,114,66,162,3.8,2.2,5.4,"92,488","82,976","102,000",WY
3192,56041,WY,Uinta County,7.0,8.0,7.0,8.0,"1,697","1,279","2,115",...,354,210,498,8.3,4.9,11.7,"71,246","61,861","80,631",WY
3193,56043,WY,Washakie County,7.0,11.0,7.0,11.0,739,537,941,...,148,87,209,11.7,6.8,16.6,"58,532","50,245","66,819",WY
3194,56045,WY,Weston County,7.0,9.0,7.0,9.0,679,519,839,...,113,66,160,11.2,6.6,15.8,"58,901","50,079","67,723",WY

In [36]:
Unplanned_Vist = pd.read_csv("/home/mcleodgunne/Mod2HW/Unplanned_Hospital_Visits-State.csv")
Unplanned_Vist

,State,Measure ID,Measure Name,Number of Hospitals Worse,Number of Hospitals Same,Number of Hospitals Better,Number of Hospitals Too Few,Footnote,Start Date,End Date,Number of Hospitals Fewer,Number of Hospitals Average,Number of Hospitals More,Number of Hospitals Too Small
0,AK,EDAC_30_AMI,Hospital return days for heart attack patients,Not Applicable,Not Applicable,Not Applicable,Not Applicable,NaN,07/01/2016,06/30/2019,1,4,0,13
1,AK,EDAC_30_HF,Hospital return days for heart failure patients,Not Applicable,Not Applicable,Not Applicable,Not Applicable,NaN,07/01/2016,06/30/2019,0,7,2,13
2,AK,EDAC_30_PN,Hospital return days for pneumonia patients,Not Applicable,Not Applicable,Not Applicable,Not Applicable,NaN,07/01/2016,06/30/2019,2,9,4,7
3,AK,OP_32,Rate of unplanned hospital visits after colono...,0,7,0,7,NaN,01/01/2017,12/24/2019,Not Applicable,Not Applicable,Not Applicable,Not Applicable
4,AK,OP_35_ADM,Rate of inpatient admissions for patients rece...,0,8,0,5,NaN,01/01/2019,12/01/2019,Not Applicable,Not Applicable,Not Applicable,Not Applicable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
779,WY,READM_30_COPD,Rate of readmission for chronic obstructive pu...,0,21,0,7,NaN,07/01/2016,06/30/2019,Not Applicable,Not Applicable,Not Applicable,Not Applicable
780,WY,READM_30_HF,Heart failure (HF) 30-Day Readmission Rate,0,20,0,8,NaN,07/01/2016,06/30/2019,Not Applicable,Not Applicable,Not Applicable,Not Applicable
781,WY,READM_30_HIP_KNEE,Rate of readmission after hip/knee replacement,0,15,0,5,NaN,07/01/2016,06/30/2019,Not Applicable,Not Applicable,Not Applicable,Not Applicable
782,WY,READM_30_HOSP_WIDE,Rate of readmission after discharge from hospi...,0,28,0,0,NaN,07/01/2018,06/30/2019,Not Applicable,Not Applicable,Not Applicable,Not Applicable
783,WY,READM_30_PN,Pneumonia (PN) 30-Day Readmission Rate,0,22,0,6,NaN,07/01/2016,06/30/2019,Not Applicable,Not Applicable,Not Applicable,Not Applicable

In [58]:
pd.concat([Unplanned_Vist, Poverty_Estimates])

,State,Measure Name,Number_Fewer,Number_More,FIPS_code,Stabr,Area_name,Rural-urban_Continuum_Code_2003,Urban_Influence_Code_2003,Rural-urban_Continuum_Code_2013,...,CI90UB017P_2020,POV517_2020,CI90LB517_2020,CI90UB517_2020,PCTPOV517_2020,CI90LB517P_2020,CI90UB517P_2020,MEDHHINC_2020,CI90LBINC_2020,CI90UBINC_2020
0,AK,Hospital return days for heart attack patients,1,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,AL,Hospital return days for heart attack patients,4,5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,AR,Hospital return days for heart attack patients,2,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,AZ,Hospital return days for heart attack patients,5,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,CA,Hospital return days for heart attack patients,30,52,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3190,WY,NaN,NaN,NaN,56037.0,WY,Sweetwater County,5.0,8.0,5.0,...,11.4,587,360,814,7.3,4.5,10.1,"70,583","61,835","79,331"
3191,WY,NaN,NaN,NaN,56039.0,WY,Teton County,7.0,8.0,7.0,...,6.0,114,66,162,3.8,2.2,5.4,"92,488","82,976","102,000"
3192,WY,NaN,NaN,NaN,56041.0,WY,Uinta County,7.0,8.0,7.0,...,13.4,354,210,498,8.3,4.9,11.7,"71,246","61,861","80,631"
3193,WY,NaN,NaN,NaN,56043.0,WY,Washakie County,7.0,11.0,7.0,...,15.5,148,87,209,11.7,6.8,16.6,"58,532","50,245","66,819"
3194,WY,NaN,NaN,NaN,56045.0,WY,Weston County,7.0,9.0,7.0,...,17.4,113,66,160,11.2,6.6,15.8,"58,901","50,079","67,723"

In [44]:
Unplanned_Vist2 = pd.read_csv("/home/mcleodgunne/Mod2HW/Unplanned_Hospital_Visits-State.csv")
Unplanned_Vist2 >> spread(X["Measure Name"], X["Measure ID"])

,State,Number of Hospitals Worse,Number of Hospitals Same,Number of Hospitals Better,Number of Hospitals Too Few,Footnote,Start Date,End Date,Number of Hospitals Fewer,Number of Hospitals Average,...,Hospital return days for pneumonia patients,Pneumonia (PN) 30-Day Readmission Rate,Rate of emergency department (ED) visits for patients receiving outpatient chemotherapy,Rate of inpatient admissions for patients receiving outpatient chemotherapy,Rate of readmission after discharge from hospital (hospital-wide),Rate of readmission after hip/knee replacement,Rate of readmission for CABG,Rate of readmission for chronic obstructive pulmonary disease (COPD) patients,"Rate of unplanned hospital visits after colonoscopy (per 1,000 colonoscopies)",Ratio of unplanned hospital visits after hospital outpatient surgery
0,AK,0,14,0,8,NaN,07/01/2016,06/30/2019,Not Applicable,Not Applicable,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,READM_30_COPD,NaN,NaN
1,AK,0,15,0,7,NaN,07/01/2016,06/30/2019,Not Applicable,Not Applicable,...,NaN,READM_30_PN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AK,0,2,0,0,NaN,07/01/2016,06/30/2019,Not Applicable,Not Applicable,...,NaN,NaN,NaN,NaN,NaN,NaN,READM_30_CABG,NaN,NaN,NaN
3,AK,0,20,1,1,NaN,07/01/2018,06/30/2019,Not Applicable,Not Applicable,...,NaN,NaN,NaN,NaN,READM_30_HOSP_WIDE,NaN,NaN,NaN,NaN,NaN
4,AK,0,4,1,13,NaN,07/01/2016,06/30/2019,Not Applicable,Not Applicable,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,WY,0,8,0,10,NaN,01/01/2019,12/01/2019,Not Applicable,Not Applicable,...,NaN,NaN,OP_35_ED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
727,WY,1,7,0,10,NaN,01/01/2019,12/01/2019,Not Applicable,Not Applicable,...,NaN,NaN,NaN,OP_35_ADM,NaN,NaN,NaN,NaN,NaN,NaN
728,WY,Not Applicable,Not Applicable,Not Applicable,Not Applicable,NaN,07/01/2016,06/30/2019,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
729,WY,Not Applicable,Not Applicable,Not Applicable,Not Applicable,NaN,07/01/2016,06/30/2019,3,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
730,WY,Not Applicable,Not Applicable,Not Applicable,Not Applicable,NaN,07/01/2016,06/30/2019,5,14,...,EDAC_30_PN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
Unplanned_Vist >> summarise(Number_For_Heart_Attack = (X['Measure Name'].count()))

   Number_For_Heart_Attack
0                       52

In [47]:
Unplanned_Vist = (Unplanned_Vist >> filter_by(X["Measure Name"]== "Hospital return days for heart attack patients")
                                 >> select(X.State, X["Measure Name"], X["Number of Hospitals Fewer"], X["Number of Hospitals More"])
                                 >> filter_by(X["Number of Hospitals Fewer"] != "Not Available")
                                 >> mutate(Number_Fewer = X["Number of Hospitals Fewer"])
                                 >> mutate(Number_More = X["Number of Hospitals More"])
                                 >> drop(X["Number of Hospitals More"], X["Number of Hospitals Fewer"])
                                 )
Unplanned_Vist

,State,Measure Name,Number_Fewer,Number_More
0,AK,Hospital return days for heart attack patients,1,0
14,AL,Hospital return days for heart attack patients,4,5
28,AR,Hospital return days for heart attack patients,2,6
56,AZ,Hospital return days for heart attack patients,5,7
70,CA,Hospital return days for heart attack patients,30,52
84,CO,Hospital return days for heart attack patients,13,2
98,CT,Hospital return days for heart attack patients,1,3
112,DC,Hospital return days for heart attack patients,0,5
126,DE,Hospital return days for heart attack patients,0,1
140,FL,Hospital return days for heart attack patients,6,62
154,GA,Hospital return days for heart attack patients,5,12
182,HI,Hospital return days for heart attack patients,2,2
196,IA,Hospital return days for heart attack patients,10,0
210,ID,Hospital return days for heart attack patients,5,0
224,IL,Hospital return days for heart attack patients,3,22
238,IN,Hospital return days for heart attack patients,10,11
252,KS,Hospital return days for heart attack patients,6,0
266,KY,Hospital return days for heart attack patients,1,10
280,LA,Hospital return days for heart attack patients,3,11
294,MA,Hospital return days for heart attack patients,1,14
308,MD,Hospital return days for heart attack patients,5,11
322,ME,Hospital return days for heart attack patients,4,2
336,MI,Hospital return days for heart attack patients,11,19
350,MN,Hospital return days for heart attack patients,5,0
364,MO,Hospital return days for heart attack patients,3,11
392,MS,Hospital return days for heart attack patients,3,5
406,MT,Hospital return days for heart attack patients,1,0
420,NC,Hospital return days for heart attack patients,11,5
434,ND,Hospital return days for heart attack patients,0,0
448,NE,Hospital return days for heart attack patients,4,1
462,NH,Hospital return days for heart attack patients,2,0
476,NJ,Hospital return days for heart attack patients,0,30
490,NM,Hospital return days for heart attack patients,4,1
504,NV,Hospital return days for heart attack patients,2,3
518,NY,Hospital return days for heart attack patients,3,49
532,OH,Hospital return days for heart attack patients,6,15
546,OK,Hospital return days for heart attack patients,5,5
560,OR,Hospital return days for heart attack patients,6,0
574,PA,Hospital return days for heart attack patients,11,17
588,PR,Hospital return days for heart attack patients,0,4
602,RI,Hospital return days for heart attack patients,0,2
616,SC,Hospital return days for heart attack patients,6,5
630,SD,Hospital return days for heart attack patients,2,0
644,TN,Hospital return days for heart attack patients,7,7
658,TX,Hospital return days for heart attack patients,14,42
672,UT,Hospital return days for heart attack patients,5,0
686,VA,Hospital return days for heart attack patients,6,9
714,VT,Hospital return days for heart attack patients,2,0
728,WA,Hospital return days for heart attack patients,8,2
742,WI,Hospital return days for heart attack patients,9,5
756,WV,Hospital return days for heart attack patients,0,4
770,WY,Hospital return days for heart attack patients,2,0

In [54]:
Poverty_Unplanned_Heart_Attack = (Poverty_Estimates >> left_join(Unplanned_Vist, by= 'State'))
Poverty_Unplanned_Heart_Attack

,FIPS_code,Stabr,Area_name,Rural-urban_Continuum_Code_2003,Urban_Influence_Code_2003,Rural-urban_Continuum_Code_2013,Urban_Influence_Code_2013,POVALL_2020,CI90LBALL_2020,CI90UBALL_2020,...,PCTPOV517_2020,CI90LB517P_2020,CI90UB517P_2020,MEDHHINC_2020,CI90LBINC_2020,CI90UBINC_2020,State,Measure Name,Number_Fewer,Number_More
0,0,US,United States,NaN,NaN,NaN,NaN,"38,371,394","38,309,115","38,433,673",...,14.9,14.9,14.9,"67,340","67,251","67,429",US,NaN,NaN,NaN
1,1000,AL,Alabama,NaN,NaN,NaN,NaN,"714,568","695,249","733,887",...,19.7,18.7,20.7,"53,958","53,013","54,903",AL,Hospital return days for heart attack patients,4,5
2,1001,AL,Autauga County,2.0,2.0,2.0,2.0,"6,242","4,930","7,554",...,14.5,9.7,19.3,"67,565","59,132","75,998",AL,Hospital return days for heart attack patients,4,5
3,1003,AL,Baldwin County,4.0,5.0,3.0,2.0,"20,189","15,535","24,843",...,11.8,7.5,16.1,"71,135","66,540","75,730",AL,Hospital return days for heart attack patients,4,5
4,1005,AL,Barbour County,6.0,6.0,6.0,6.0,"5,548","4,210","6,886",...,35.8,24.4,47.2,"38,866","33,510","44,222",AL,Hospital return days for heart attack patients,4,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3190,56037,WY,Sweetwater County,5.0,8.0,5.0,8.0,"3,187","2,435","3,939",...,7.3,4.5,10.1,"70,583","61,835","79,331",WY,Hospital return days for heart attack patients,2,0
3191,56039,WY,Teton County,7.0,8.0,7.0,8.0,"1,207",896,"1,518",...,3.8,2.2,5.4,"92,488","82,976","102,000",WY,Hospital return days for heart attack patients,2,0
3192,56041,WY,Uinta County,7.0,8.0,7.0,8.0,"1,697","1,279","2,115",...,8.3,4.9,11.7,"71,246","61,861","80,631",WY,Hospital return days for heart attack patients,2,0
3193,56043,WY,Washakie County,7.0,11.0,7.0,11.0,739,537,941,...,11.7,6.8,16.6,"58,532","50,245","66,819",WY,Hospital return days for heart attack patients,2,0
3194,56045,WY,Weston County,7.0,9.0,7.0,9.0,679,519,839,...,11.2,6.6,15.8,"58,901","50,079","67,723",WY,Hospital return days for heart attack patients,2,0